#!/bin/bash

# Job name to check
JOB_NAME="your_job_name"

# Check if the job is running
JOB_STATUS=$(autorep -J "$JOB_NAME" -q | grep "RU")

if [[ $JOB_STATUS == *"RU"* ]]; then
    echo "Job $JOB_NAME is currently running."
    
    # Optionally, check for some condition
    if [ some_condition ]; then
        # Kill the running job
        echo "Killing job $JOB_NAME..."
        sendevent -E KILLJOB -J "$JOB_NAME"
        sleep 5  # Wait for the job to stop
        
        # On Ice the job
        echo "Putting job $JOB_NAME on ice..."
        sendevent -E ON_ICE -J "$JOB_NAME"
    else
        echo "Condition not met, not killing the job."
    fi
else
    echo "Job $JOB_NAME is not running."
    
    # Put the job on ice directly
    echo "Putting job $JOB_NAME on ice..."
    sendevent -E ON_ICE -J "$JOB_NAME"
fi